workspace:
  base: /workspace
  path: app

when:
  - event: [push, tag]
    branch: main
    path:
      include: [".woodpecker/build-ssh.yml", "ssh/**"]

steps:
  build-docker:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/ssh
      username: eleith
      dockerfile: ssh/Dockerfile
      context: ssh
      registry: https://git.eleith.com
      auto_tag: true
      password:
        from_secret: gitea_docker_registry
  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
