workspace:
  base: /workspace
  path: app

when:
  - event: push
    branch: main
    path:
      include: [".woodpecker/build-ssh.yml", "ssh/**"]
  - event: tag
    ref: "refs/tags/ssh/v*.*.*"

steps:
  extract-semver-tags:
    image: alpine/git:latest
    commands:
      - |
        VERSION_FULL="${CI_COMMIT_TAG#ssh/v}"
        VERSION_MAJOR=$(echo "$VERSION_FULL" | cut -d. -f1)
        VERSION_MINOR=$(echo "$VERSION_FULL" | cut -d. -f2)

        SEMVER_FULL="$VERSION_FULL"
        SEMVER_MAJOR_MINOR="$VERSION_MAJOR.$VERSION_MINOR"
        SEMVER_MAJOR="$VERSION_MAJOR"

        echo "Extracted versions: $SEMVER_FULL, $SEMVER_MAJOR_MINOR, $SEMVER_MAJOR"
        echo -e "$SEMVER_FULL\n$SEMVER_MAJOR\n$SEMVER_MAJOR_MINOR" > .tags
    when:
      - event: tag

  build-docker-main:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/ssh
      username: eleith
      dockerfile: ssh/Dockerfile
      context: ssh
      registry: https://git.eleith.com
      password:
        from_secret: gitea_docker_registry
      tags: latest
    when:
      - event: push
        branch: main

  build-docker-tag:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/ssh
      username: eleith
      dockerfile: ssh/Dockerfile
      context: ssh
      registry: https://git.eleith.com
      password:
        from_secret: gitea_docker_registry
      tags_file: .tags
    when:
      - event: tag

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
